name: Auto-Building Jekyll and Deploying to GitHub Pages

#触发器：在代码 push 到主分支时运行。
on:
  push:
    branches:
      - main  # 当'main'分支有变化时触发

###  任务（大致可拆分为）：
###    1 检出代码。
###    2 配置 Ruby 环境（同时或者紧接着）安装Jekyll及其依赖。
###    3 构建Jekyll网站。
###    4 将静态文件部署到 gh-pages 分支。

jobs:
  build_and_deploy: #起名为‘构建和部署’
    runs-on: ubuntu-latest

    steps:
    
      # Step 1: 检出代码（将仓库的源代码拉取到运行器环境中）
      - name: Checkout Code 
        uses: actions/checkout@v4
    
      # Step 2: 配置Ruby环境（随便指定一个3.2.4吧跟本地环境一致）
      - name: Setup Ryby -to match local env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4' 
          # Step 3: 本质上是运行 "bundle install "抓取Gemfile里指定的依赖并自动缓存已安装的gem
          bundler-cache: true
      
      # Step 3: 同上，抓取依赖, Use GitHub Actions' cache to cache dependencies on servers
      # 但是不仅可以抓取并缓存Gemfile指定的Bundler依赖，也能缓存非Bundler工具的其他文件（如 npm）在其他自定义目录（如 _site）
      #- name: Cache Dependencies
      #  uses: actions/cache@v4
      #  with:
      #      path: vendor/bundle
      #      key: ${{ runner.os }}-gemfile-${{ hashFiles('**/Gemfile.lock') }}
      #      restore-keys: |
      #        ${{ runner.os }}-gemfile-
              
      # Step 4: 构建Jekyll 网站（结果似乎是缓存在_site目录的静态文件）
      - name: Build Jekyll site
        run: bundle exec jekyll build
          
      # Step 5: 部署到gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
