name: Auto-Building Jekyll and Deploying to GitHub Pages

#触发器：在代码 push 到主分支时运行。
on:
  push:
    branches:
      - main  # 当'main'分支有变化时触发

###  任务（大致可拆分为）：
###    1 检出代码。
###    2 配置 Ruby 环境（同时或者紧接着）安装Jekyll及其依赖。
###    3 构建Jekyll网站。
###    4 将静态文件部署到 gh-pages 分支。

jobs:
  build: #起名为‘构建’
    runs-on: ubuntu-latest

    steps:
    
      # Step 1: 检出代码（将仓库的源代码拉取到运行器环境中）
      - name: Checkout Code 
        uses: actions/checkout@v4
    
      # Step 2: 配置Ruby环境（随便指定一个3.2.4吧跟本地环境一致）
      - name: Setup Ryby -to match local env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4' 
          # Step 3: 本质上是运行 "bundle install "抓取Gemfile里指定的依赖并自动缓存已安装的gem
          bundler-cache: true
      
      # Step 3: 同上，抓取依赖, Use GitHub Actions' cache to cache dependencies on servers
      # 但是不仅可以抓取并缓存Gemfile指定的Bundler依赖，也能缓存非Bundler工具的其他文件（如 npm）在其他自定义目录（如 _site）
      #- name: Cache Dependencies
      #  uses: actions/cache@v4
      #  with:
      #      path: vendor/bundle
      #      key: ${{ runner.os }}-gemfile-${{ hashFiles('**/Gemfile.lock') }}
      #      restore-keys: |
      #        ${{ runner.os }}-gemfile-
              
      # Step 4: 构建Jekyll 网站（结果似乎是缓存在_site目录的静态文件）
      - name: Build Jekyll site
        run: bundle exec jekyll build
          
      # Step 5: 上传构建的内容作为工件
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site
          name: my-Pages #新增，给built好的工件命名？
  
  deploy: 
    # 部署工作流需要在构建成功后运行
    needs: build # Add a dependency to the build job
    runs-on: ubuntu-latest # Specify runner

    permissions: # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      pages: write  # 允许写入权限以进行 GitHub Pages 部署
      id-token: write  # 用于身份验证
    
    # Deploy to the github-pages environment
    # environment:
      #name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      # Step 6: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
